"""Stable reason codes.

Every decision branch and every rejection emits one of these. The strings are
part of the ledger's on-disk contract: rename one and historical records stop
being comparable. Add new codes rather than repurposing existing ones.
"""

from __future__ import annotations

# --- configuration ---------------------------------------------------------
CONFIG_INVALID = "CONFIG_INVALID"
ARMED_REQUIREMENT_MISSING = "ARMED_REQUIREMENT_MISSING"
ARMED_ENVIRONMENT_GATE_CLOSED = "ARMED_ENVIRONMENT_GATE_CLOSED"

# --- watcher ---------------------------------------------------------------
METRICS_TIMEOUT = "METRICS_TIMEOUT"
WORKBOOK_UNREADABLE = "WORKBOOK_UNREADABLE"
SHEET_SET_MISMATCH = "SHEET_SET_MISMATCH"
COLUMN_MISSING = "COLUMN_MISSING"
NUMERIC_COERCION_FAILED = "NUMERIC_COERCION_FAILED"

# --- recording selection ---------------------------------------------------
RECORDING_NOT_FOUND = "RECORDING_NOT_FOUND"
RECORDING_AMBIGUOUS = "RECORDING_AMBIGUOUS"
RECORDING_ALREADY_CONSUMED = "RECORDING_ALREADY_CONSUMED"
ACTIVITY_INSTANCE_NOT_FOUND = "ACTIVITY_INSTANCE_NOT_FOUND"
ACTIVITY_INSTANCE_AMBIGUOUS = "ACTIVITY_INSTANCE_AMBIGUOUS"

# --- quality control -------------------------------------------------------
RATE_MISSING = "RATE_MISSING"
RATE_NOT_FINITE = "RATE_NOT_FINITE"
RATE_NEGATIVE = "RATE_NEGATIVE"
ACTIVE_AREA_MISSING = "ACTIVE_AREA_MISSING"
ACTIVE_AREA_BELOW_MINIMUM = "ACTIVE_AREA_BELOW_MINIMUM"
ACTIVE_ELECTRODES_BELOW_MINIMUM = "ACTIVE_ELECTRODES_BELOW_MINIMUM"
SINGLE_ELECTRODE_MEAN = "SINGLE_ELECTRODE_MEAN"
DURATION_MISSING = "DURATION_MISSING"
DURATION_OUT_OF_RANGE = "DURATION_OUT_OF_RANGE"
CONFIGURATION_COUNT_UNEXPECTED = "CONFIGURATION_COUNT_UNEXPECTED"
ACQUISITION_MISMATCH = "ACQUISITION_MISMATCH"
ANALYSIS_PARAMETER_MISMATCH = "ANALYSIS_PARAMETER_MISMATCH"
RECORDING_WINDOW_OUTSIDE_CYCLE = "RECORDING_WINDOW_OUTSIDE_CYCLE"

# --- policy ----------------------------------------------------------------
BASELINE_RECORDED = "BASELINE_RECORDED"
THRESHOLD_REACHED = "THRESHOLD_REACHED"
BELOW_THRESHOLD_STEP_UP = "BELOW_THRESHOLD_STEP_UP"
MAX_AMPLITUDE_REACHED = "MAX_AMPLITUDE_REACHED"
MAX_AMPLITUDE_EXCEEDED = "MAX_AMPLITUDE_EXCEEDED"
MAX_CYCLES_REACHED = "MAX_CYCLES_REACHED"
MAX_DURATION_REACHED = "MAX_DURATION_REACHED"
CUMULATIVE_STIMULATION_LIMIT_REACHED = "CUMULATIVE_STIMULATION_LIMIT_REACHED"

# --- hardware --------------------------------------------------------------
ADAPTER_UNAVAILABLE = "ADAPTER_UNAVAILABLE"
API_ERROR = "API_ERROR"
AMBIGUOUS_STIM_RECEIPT = "AMBIGUOUS_STIM_RECEIPT"
PREFLIGHT_FAILED = "PREFLIGHT_FAILED"

# --- operator --------------------------------------------------------------
OPERATOR_STOP = "OPERATOR_STOP"
RECOVERY_REQUIRED = "RECOVERY_REQUIRED"
